apiVersion: v1
kind: ConfigMap
metadata:
  name: fluent-bit-cluster-info
  namespace: amazon-cloudwatch
  labels:
    app.kubernetes.io/name: fluent-bit
data:
  cluster.name: my-eks-cluster
  cluster.region: us-east-1
  read.head: "Off"
  http.server: "On"
  http.port: "2020"
  logs.region: us-east-1
